# Generated by Django 5.2.5 on 2025-08-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='agent_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
