# Generated by Django 5.2.5 on 2025-08-14 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending'), ('Due for Renewal', 'Due for Renewal')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='PolicyRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_date', models.DateField()),
                ('new_sum_assured', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_premium_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_end_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='policy.policy')),
            ],
            options={
                'ordering': ['-renewal_date'],
            },
        ),
    ]
