# Generated by Django 5.2.5 on 2025-08-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_alter_policy_status_policyrenewal'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
