# Generated by Django 5.2.5 on 2025-08-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0003_policy_deleted_at_policy_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='policy_document',
            field=models.FileField(blank=True, null=True, upload_to='policies/'),
        ),
    ]
