# Generated by Django 5.2.5 on 2025-08-17 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_alter_familyhead_email'),
        ('policy', '0004_alter_policy_policy_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='client.familyhead'),
        ),
    ]
