# Generated by Django 5.2.5 on 2025-08-17 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_alter_familyhead_email'),
        ('policy', '0005_policy_holder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='client.familyhead'),
        ),
    ]
