# Generated by Django 5.2.5 on 2025-08-17 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0006_alter_policy_holder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='object_id',
        ),
    ]
