# Generated by Django 5.2.5 on 2025-08-22 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0012_remove_familyhead_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('policy', 'Policy Document'), ('id_proof', 'ID Proof'), ('address_proof', 'Address Proof'), ('income_proof', 'Income Proof'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_by', models.CharField(max_length=100)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('family_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.familyhead')),
                ('family_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.familymember')),
                ('firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.firm')),
            ],
        ),
    ]
