# Generated by Django 5.2.5 on 2025-08-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True)),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile_no', models.CharField(max_length=15, unique=True)),
                ('whatsapp_no', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('alternate_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('agent_code', models.CharField(max_length=50, unique=True)),
                ('joining_date', models.DateField()),
                ('qualification', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField(blank=True, help_text='Experience in years', null=True)),
                ('previous_company', models.CharField(blank=True, max_length=255, null=True)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('license_expiry_date', models.DateField()),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('commission_type', models.CharField(max_length=50)),
                ('commission_rate', models.CharField(max_length=50)),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('assigned_territory', models.CharField(blank=True, max_length=255, null=True)),
                ('territory_type', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(upload_to='sub_agent/photos/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='sub_agent/resumes/')),
                ('license_document', models.FileField(upload_to='sub_agent/licenses/')),
                ('identity_proof', models.FileField(upload_to='sub_agent/identity/')),
                ('address_proof', models.FileField(upload_to='sub_agent/address_proof/')),
                ('bank_passbook', models.FileField(upload_to='sub_agent/passbooks/')),
                ('emergency_contact_name', models.CharField(max_length=255)),
                ('emergency_contact_relation', models.CharField(max_length=50)),
                ('emergency_contact_mobile', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
