# Generated by Django 5.2.5 on 2025-08-14 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subagent',
            name='account_holder_name',
        ),
        migrations.RemoveField(
            model_name='subagent',
            name='address_proof',
        ),
        migrations.RemoveField(
            model_name='subagent',
            name='alternate_email',
        ),
        migrations.RemoveField(
            model_name='subagent',
            name='assigned_territory',
        ),
        migrations.RemoveField(
            model_name='subagent',
            name='bank_passbook',
        ),
        migrations.RemoveField(
            model_name='subagent',
            name='commission_rate',
        ),
        migrations.RemoveField(
            model_name='subagent',
            name='commission_type',
        ),
        migrations.RemoveField(
            model_name='subagent',
            name='emergency_contact_mobile',
        ),
        migrations.RemoveField(
            model_name='subagent',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='subagent',
            name='emergency_contact_relation',
        ),
        migrations.RemoveField(
            model_name='subagent',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='subagent',
            name='identity_proof',
        ),
        migrations.RemoveField(
            model_name='subagent',
            name='ifsc_code',
        ),
        migrations.RemoveField(
            model_name='subagent',
            name='license_document',
        ),
        migrations.RemoveField(
            model_name='subagent',
            name='license_expiry_date',
        ),
        migrations.RemoveField(
            model_name='subagent',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='subagent',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='subagent',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='subagent',
            name='target_amount',
        ),
        migrations.RemoveField(
            model_name='subagent',
            name='territory_type',
        ),
        migrations.RemoveField(
            model_name='subagent',
            name='whatsapp_no',
        ),
    ]
