# Generated by Django 5.2.5 on 2025-08-14 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_remove_subagent_account_holder_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subagent',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='subagent',
            name='bank_name',
        ),
    ]
