# Generated by Django 5.2.5 on 2025-08-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_remove_subagent_account_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subagent',
            name='previous_company',
        ),
        migrations.RemoveField(
            model_name='subagent',
            name='specialization',
        ),
        migrations.AddField(
            model_name='subagent',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended')], default='Active', max_length=20),
        ),
    ]
