# Generated by Django 5.2.5 on 2025-08-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('address1', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('marriage_status', models.CharField(max_length=20)),
                ('aadhar_no', models.CharField(max_length=20)),
                ('group_type', models.CharField(max_length=20)),
                ('business_type', models.CharField(max_length=50)),
                ('client_status', models.CharField(max_length=20)),
                ('joined_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Family Head',
                'verbose_name_plural': 'Family Heads',
                'ordering': ['-created_at'],
            },
        ),
    ]
