# Generated by Django 5.2.5 on 2025-08-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_familymember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=255)),
                ('firm_type', models.CharField(max_length=100)),
                ('contact_person_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=15)),
                ('whatsapp_no', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('address1', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('business_type', models.CharField(max_length=100)),
                ('pan_card', models.CharField(blank=True, max_length=10, null=True)),
                ('registration_file', models.FileField(blank=True, null=True, upload_to='firm_files/registrations/')),
                ('gst_file', models.FileField(blank=True, null=True, upload_to='firm_files/gst/')),
                ('pan_file', models.FileField(blank=True, null=True, upload_to='firm_files/pan/')),
                ('firm_logo', models.ImageField(blank=True, null=True, upload_to='firm_files/logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Firm',
                'verbose_name_plural': 'Firms',
                'ordering': ['-created_at'],
            },
        ),
    ]
