# Generated by Django 5.2.5 on 2025-08-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_firm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familyhead',
            options={},
        ),
        migrations.AlterModelOptions(
            name='familymember',
            options={},
        ),
        migrations.AlterModelOptions(
            name='firm',
            options={},
        ),
        migrations.AddField(
            model_name='familyhead',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familyhead',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familymember',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='firm',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firm',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
