# Generated by Django 5.2.5 on 2025-08-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_familyhead_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyhead',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
