# Generated by Django 5.2.5 on 2025-08-17 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_alter_familyhead_dob_alter_familymember_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firm',
            name='firm_logo',
        ),
        migrations.RemoveField(
            model_name='firm',
            name='gst_file',
        ),
        migrations.RemoveField(
            model_name='firm',
            name='pan_card',
        ),
        migrations.RemoveField(
            model_name='firm',
            name='pan_file',
        ),
        migrations.RemoveField(
            model_name='firm',
            name='registration_file',
        ),
        migrations.RemoveField(
            model_name='firm',
            name='whatsapp_no',
        ),
        migrations.AddField(
            model_name='firm',
            name='family_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.familyhead'),
        ),
    ]
