# Generated by Django 5.2.5 on 2025-08-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_remove_firm_firm_logo_remove_firm_gst_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyhead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
