# Generated by Django 5.2.5 on 2025-08-21 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_familyhead_address_familyhead_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyhead',
            name='age',
        ),
    ]
