# Generated by Django 5.2.5 on 2025-08-17 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0004_remove_subagent_previous_company_and_more'),
        ('client', '0010_alter_familyhead_email'),
        ('policy', '0006_alter_policy_holder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Assigned', 'Assigned')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_subagent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent.subagent')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='client.familyhead')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='policy.policy')),
            ],
        ),
    ]
