# Generated by Django 5.2.5 on 2025-08-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0002_alter_inquiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='inquiry_documents/'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
    ]
